name = "cf-style-greyscale"
main = "cf-style-greyscale.js"
compatibility_date = "2025-11-27"

[[routes]]
pattern = "bugs.1f616emo.xyz/*"
zone_id = "3c79f7e2fe7d64bbe330d408c8b0a63e"

[[routes]]
pattern = "lingva.1f616emo.xyz/*"
zone_id = "3c79f7e2fe7d64bbe330d408c8b0a63e"
